### ISSUE TITLE
Destroyed unconsumed future

### ISSUE THREAD

**Issue by karantin2020** [zielmicha/reactor.nim#7]
Hello. I have that code:

``` nim
proc request*(conn: HttpConnection, 
              http_method, 
              path: string, 
              query: string = ""): Future[HttpResponse] {.async.} =
  return await conn.request(newHttpRequest(http_method, path & query, ""))

when isMainModule:
  proc main() {.async.} =    
    const cnt = 500
    let cnn = await newHttpConnection("127.0.0.1", port=8080)
    var arres = newSeq[Future[HttpResponse]](cnt)
    var arresp = newSeq[HttpResponse](cnt)
    for i in 0..cnt-1:
      arres[i] = request(cnn, "GET", "/hello")
    var rsp: HttpResponse
    var ans: string = ""
    for j in 0..cnt-1:
      arresp[j] = await arres[j]
      ans = await arresp[j].dataStream.readUntilEof()
    echo arresp[^1]
    echo ans

  main().runMain()
```

Code works fine. But when I change cnt to 5000 I get error:

``` sh
Destroyed unconsumed future Future just(HttpResponse(statusCode=200, headers={date=...
```

What is the reason of that error?

**Comment by zielmicha** [comment]
It's strange that this code works at all. `request` does both `sendRequest` and `readResponse` - that means that 500 `readResponse`s are not ordered (i.e. their code executes in undefined order). 

You either need to create new connection for each request or properly use HTTP pipelining. (for pipelining you need to, in parallel, serially send all requests using `sendRequest` and serially read all responses using `readResponse`). There is also `SerialQueue` type in `asyncutil` that is meant to make using pipelining easy.

(I get different error, but the error you get means that you have not `await`ed some of Futures you have created, probably because your code finished with other error)
